settings:
    prefix: "§8§l❘ §3Game§7Prefix §8§l❘ "
    join-title: "§eGameTitle"
    join-subtitle: "§7"
    join-sound: "NOTE_STICKS"
    game-type: "GameType"
    lobby:
        world: 'world'
        teleport-location:
            x: 0.0
            y: 100.0
            z: 0.0
            yaw: 0.0
            pitch: 0.0